name = "newsgenie-worker"
main = "src/index.js"
compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "BYTES_DO", class_name = "BytesStore" }
]

[[migrations]]
tag = "v1"
new_classes = ["BytesStore"]


